name: Rust build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  analyze:
    name: Static analysis & linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2
      - name: Unit tests
        run: cargo test --lib --bins --locked
      - name: E2E tests
        run: cargo test --test cli --locked
      - run: cargo build --release --locked
